# SPDX-FileCopyrightText: Copyright DB InfraGO AG
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /src/capellambse_context_diagrams/interop
    schedule:
      interval: weekly
      day: wednesday
    groups:
      js-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: chore
